# https://gitlab.com/gitlab-org/gitlab-ci-yml/tree/master
concurrent = 1
check_interval = 0

[[runners]]
  name = "ubuntu"
  url = "http://192.168.1.12/ci"
  token = "b1564987d0f0f8dc9fbf38f5ed2e6d"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "maven:3.5-jdk-8"
    privileged = false
    disable_cache = false
    volumes = ["/cache","/root/m2:/root/.m2"]
    pull_policy = "if-not-present"
    shm_size = 0
  [runners.cache]
    Insecure = false
