#!/bin/bash

VMHOME=/home/rugal/VM
VM_CONFIG_HOME=/etc/libvirt/qemu
#source ../common/tool.sh

if [ $# == 0 ]
then
    exit
fi

virsh destroy $1
virsh undefine $1

rm -rf  "$VMHOME/$1"
sudo rm  "$VM_CONFIG_HOME/$1"
